language: node_js
node_js:
 - "node"
addons:
  postgresql: "9.5"
before_script:
  - psql -c 'create database chinchay_test;' -U postgres
  - psql -c 'create database chinchay2;' -U postgres
  - npm i knex -g
  - knex migrate:latest --env test
  - node knexOtherMigrate.js
script:
  - npm run test
  - npm run coverage
  - npm run linter
after_success:
  - npm run coveralls
before_deploy:
  - npm version patch
deploy:
  - provider: npm
    email: antonio.fontainecorrea@gmail.com
    api_key: $NPM_TOKEN
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: .travis/pu.sh
    on:
      branch: master
      tags: false
